In [4]:
import pandas as pd
import plotly_express as px

In [7]:
df = pd.read_csv("../my_gurgaon_properties_missing_value_imputation.csv")
latlong = pd.read_csv("datasets/latlong.csv")

In [3]:
latlong['latitude'] = latlong['coordinates'].str.split(',').str.get(0).str.split('°').str.get(0).astype('float')
latlong['longitude'] = latlong['coordinates'].str.split(',').str.get(1).str.split('°').str.get(0).astype('float')

In [4]:
new_df = df.merge(latlong, on='sector')

In [5]:
group_df = new_df.groupby("sector").mean(numeric_only=True)[['price','price_per_sqft','built_up_area','latitude','longitude']]
group_df

                price  price_per_sqft  built_up_area  latitude  longitude
sector
gwal pahari  3.192222     9585.777778    3056.166667   28.4484    77.0210
manesar      0.962258     4608.064516    2027.367742   28.3515    76.9428
sector 1     1.860000     8249.833333    2327.833333   28.3663    76.9456
sector 10    2.092857    11866.571429    1908.857143   28.4537    77.0009
sector 102   1.696636    10603.822430    1556.130841   28.4750    76.9715
...               ...             ...            ...       ...        ...
sector 91    1.648235     7586.117647    2028.647059   28.4014    76.9225
sector 92    0.934000     5928.290000    1571.341800   28.4079    76.9153
sector 93    0.848889     8009.888889    1017.000000   28.4153    76.9326
sector 95    0.480545     5602.509091     995.981818   28.4172    76.9081
sector 99    1.008095     6412.166667    1364.214286   28.4640    76.9614

[101 rows x 5 columns]

In [8]:
# fig = px.scatter_mapbox(group_df, lat="latitude", lon="longitude", color="price_per_sqft", size="built_up_area", color_continuous_scale=px.colors.cyclical.IceFire, zoom=10, mapbox_style="open-street-map", text=group_df.index)

fig = px.scatter_map(group_df, lat="latitude", lon="longitude", color="price_per_sqft", size="built_up_area", color_continuous_scale=px.colors.cyclical.IceFire, zoom=10, map_style="open-street-map", text=group_df.index)
fig.show()

In [9]:
new_df.to_csv("dataviz_1.csv", index=False)

In [5]:
df1 = pd.read_csv('../my_gurgaon_properties.csv')

In [8]:
wordcloud_df = df1.merge(df, left_index=True, right_index=True)[['features','sector']]
wordcloud_df.head()

                                            features      sector
0               ['Private Garden / Terrace', 'Park']   sector 36
1  ['Security / Fire Alarm', 'Power Back-up', 'Fe...   sector 89
2  ['Private Garden / Terrace', 'High Ceiling Hei...  sohna road
3  ['Security / Fire Alarm', 'Lift(s)', 'Maintena...   sector 92
4  ['Intercom Facility', 'Lift(s)', 'Feng Shui / ...  sector 102

In [9]:
import ast
main = []
for item in wordcloud_df['features'].dropna().apply(ast.literal_eval):
    main.extend(item)

In [11]:
from wordcloud import WordCloud
feature_text = ' '.join(main)
import pickle
pickle.dump(feature_text, open('feature_text.pkl','wb'))

In [14]:
fig = px.scatter(df, x="built_up_area", y="price", color="bedRoom", title="Area vs Price")
fig.show()